### ISSUE TITLE
Exception when Loading Unknown Locales

### ISSUE THREAD

**Issue by halfhp** [blocoio/faker#8]
Given a Faker initialization as follows:

Faker faker = new Faker("ar-AE");

A runtime exception is thrown.

Appears that If a .yml def is not available for the specified locale, initialization will fail. My expectation would be that default locale would be used instead, especially since it appears to already be pre-loaded at the time of the exception.

Most likely this is a bug but if it's intended behavior I'd lobby for a change as it's common in cloud testing environments to test on a broad range of locales and it's desirable to use localized fake data when available, as opposed to always using us english vals.

Additionally, it would be nice if locale matching was a little more generic.  For example, "zh_CN_#Hans" is a common value to retrieve from a device and will be mapped internally by the Android OS to "zh_CN".  Ideally Faker would do something similar.

**Comment by sdsantos** [comment]
@halfhp The `IllegalArgumentException` is intended.

Since the goal of the library is to port the ruby faker library, I try to follow it's behaviour. I checked it and it fails if the locale is invalid. And it doesn't support the extensions you mention (`zh_CN_#Hans`). The default locale is pre-loaded because that's also the behaviour of the ruby library. It returns the default locale is the specific locale YAML file doesn't have an entry for it, but only if the specified locale exists. Not arguing the behaviour is perfect, but I want to avoid deviating from it.

`Faker.DEFAULT_LOCALE` is a public value. I would suggest falling back to it if you receive an `IllegalArgumentException` from `new Faker("...")`.
